name: Print Software Versions
on:
  push:
    branches: [main]
jobs:
  PrintProcessingSoftware:
    runs-on: ubuntu-latest
    steps:
      - name: Check Node.js version
        run: node --version

      - name: Check npm version
        run: npm --version
  PrintDBVersions:
    runs-on: ubuntu-latest
    needs: [PrintProcessingSoftware]
    steps:
      - name: Install MongoDB
        run: |
          sudo apt-get update
          sudo apt-get install -y mongodb
      - name: Check MongoDB version
        run: mongod --version
